apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admit-pod
  namespace: tools-dev
webhooks:
  - name: admit-pod.tools-dev.svc
    clientConfig:
      service:
        name: admit
        namespace: tools-dev
        path: "/admit-pod"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKTFdOaE1CNFhEVEU1TURFeE1EQTNNek0xTWxvWERUSTVNREV3TnpBM016TTFNbG93RWpFUU1BNEdBMVVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtJS2R0dTM5Q1F5CkpJcDZ4UDhMNGw2S1MxTVF4VTB1Q2FaeXlsS2Y4bkpmQnh4MXAwdmhEWVV2andPanFMSzA0MjdIUTA5a0p3MW8Kei9xakNXMU8wV3B4TTBPYWtUUTN2WFdzM2c0dVZUL3NIelpiSjREZnMxdTdBRGdpRE8rRER3bzBFQlJ0SEdaUApBN2FuTVh1L2NnbFZ6V1RFWFp2akpxdXNYVGxJMUx5azc0cFhseU9jRFlUQll2RzBtRmlqVUJYaE1hMGhZV1JxCmpobzBLYXdzeFdycmcwQU9YZExkVTR6eGFjMlp6S0QxYm1YQmpRYzltSVVmSGZtMzZZVXJnRnBaVWZwTE1TRWUKZTI0SEFYdFBOeDNrd0tjUDIzZDQ2RERaTWVSeklIeUlESCtUUmQ2a0FqZ056R2YxMHhYTGhoNTNqOFp1aU9FRwp4U2d0QkZJdHE4MENBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSFFBb1ZCZmRKN1ZtK3lxQ0NiU1B0em1LZllMTmxNZ2s0NFcKbHBGOE1lUmY5NG9hbnVuMmlLTHYwVEhYSjBkS2NjcFFSSFlNcjNqM2tyME9Na1AvRjVyNkhNVXVvVElOSVVzVQpFRnFxZU9RckxTUFk0RXpPT3JEQVFEMGlGUXNzTnVxWENKTnY1T0ppMTh2Um9ic2EycmJhbXVFRGNNRjdFd2hICkszSFJuY0J5bllCV3hxUTd4bVBaaFhiVjhyTlNQQ0VKRng2ZndHcExqWEJhNThnMjVDcUw2RW9CMkNoV0ptbG0KMERIckhRcEk3S1hGeDU2TjZETk5XZXRkT28xYUExeFJVeXQvY3RPUU80TnlkbEMraXBVdTdjMDhTNHIycHlySApWTEg4L3EzYVZvNUY0RDFhVmFvTHZHbjhpNU5uMWNVb2k3Rlo3RGsxU3JZZDI2MUZ6UHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"