apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admit-deploy
  namespace: tools-prod
webhooks:
  - name: admit-deploy.tools-prod.svc
    clientConfig:
      service:
        name: admit
        namespace: tools-prod
        path: "/admit-deploy"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKTFdOaE1CNFhEVEU1TURnek1EQXlNamd4TWxvWERUSTVNRGd5TnpBeU1qZ3hNbG93RWpFUU1BNEdBMVVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwvenArTk04RHJTCmg2L0lUVFlFS2F1RWJyemU5MlJPTEhCTFVNdTE5eDdna1JRanBxUkJRMXl4UmU3amdnUVF6Wmp4OW1haEw2QXoKbFdoMWd4WXBMTGI2VlZMUjN4dUN5a2QwYllKeGd2K2F6Q3FLRVlnOWFlc0JsZnZiN1VMME5KdTNUL3dtaEYvSAo5WStRdzYyRHl0SkxObkZLMVFoSmZCbjRudHBOVkRSZ2RKUS9nR1NmRGZBMFl0SXVzYVY5b1g3MzhDTHQvOExmCnViUFB5QXhaUDE0ZVhWUUszNnVCdUtZTDcyYUl1Rk1XcjJPSmpaUWxSb25TbnFqVkcvd1NTVVZjd0xTbFM0aTkKaHFKOUJ0VDRsYVpVcmM5SEpqRmw3Z3FJNHlEeVN2SVRIaDRmOHVHVHR1K3ZZZW8zRFpURU1ZVlhVVjdYRDZIWApxODBxbDd6czNJa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS3Ryb0hkdU0yT3FNWVZQT29NYVE2bmhOb0Q0Q2liTlRXSjQKdkJKMmgzT0JRRyt4TXRoMDNCZWE2djQ2QmE5RC9kZDRNUmtJbmRMNU1rOC9Kd084SWlaalBPbHNEYmFDVjBmRApuMGlhbHZjUHBiR1FLN01QNHNPdnJTUzZZYXFONmFJZVloSXRqVkFQUzBJTzY4dTdPRVNOMlp6VFhiWFZIMGp5CnVVSjg0dW93S0Z6a3ZpZ2tGS2MyUzUybWVxc3k5YUUyMUNtV1BIcERJdDBEbkRBZ0Fwb0ZnMVErc3VwUkU5MEkKWU53eGV4dlloKzEzUWtLckR4S3lRME9nYitQZ29NV1NrTVlkcXN3L1MxQVJJTTFheCtPdlNFSnh6cU9kSVlJSQpBS0wySytDZHgzY1FRWlRoSUFaMytVZWNZTG9CWjU0WkNPOGQ5ZUlDaW5yOHc3VU1hRFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope: "Namespaced"