apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admit-ing-net
  namespace: tools-prod
webhooks:
  - name: admit-ing-net.tools-prod.svc
    clientConfig:
      service:
        name: admit
        namespace: tools-prod
        path: "/admit-ing-net"
      caBundle: redacted
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1beta1"]
        resources: ["ingresses"]
        scope: "Namespaced"
